name: update-readme-summary-table

# on: [workflow_dispatch]
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
    update:
      if: github.repository == 'euc-oss/euc-samples'
      runs-on: ubuntu-latest

      permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
        contents: write

      steps:
        - uses: actions/checkout@v1

        - name: Show the path
          run: ls -l ./
#            pwd
#            ${{ github.workspace }}
#            ls -l ${{ github.workspace }}

        - name: Run update-readme-summary-table.ps1 Script
          run: ./update-readme-summary-table.ps1
          shell: pwsh

        - name: Commit updates to Summary Index Tables
          run: |
            git config user.email "actions@github.com"
            git config user.name "Phil Helmling"
            git add --all
            git commit -m "update-readme-summary-table, triggered by ${GITHUB_REPOSITORY}" || echo "No changes to commit"
            git push origin HEAD:main
