name: update-readme-summary-table
on: [workflow_dispatch]

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: ./update-readme-summary-table.ps1
          shell: pwsh
        - name: Commit updates
          run: |
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions - update-readme-summary-table"
            git add --all
            git commit -m "update-readme-summary-table, triggered by ${GITHUB_REPOSITORY}" || echo "No changes to commit"
            git push
